### ISSUE TITLE
ShoRAh: list index out of range

### ISSUE THREAD

**Issue by stefanches7** [cbg-ethz/V-pipe#64]
I run the *whole* pipeline starting with usual raw reads. I.e., alignments are made within V-pipe.
ShoRAh error log:
```
Traceback (most recent call last):
  File "/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/5f9cc436/bin/shorah", line 14, in <module>
    main()
  File "/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/5f9cc436/lib/python3.6/site-packages/shorah/cli.py", line 196, in main
    args.func(args)
  File "/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/5f9cc436/lib/python3.6/site-packages/shorah/cli.py", line 75, in shotgun_run
    shotgun.main(args)
  File "/data/nasif12/home_if12/dvoretsk/projects/V-pipe-SARS/.snakemake/conda/5f9cc436/lib/python3.6/site-packages/shorah/shotgun.py", line 440, in main
    r = list(aligned_reads.keys())[0]
IndexError: list index out of range
```

**Comment by DrYak** [comment]
I presume this specific sample is your negative control ?
And you're running with this to not split in multiple `REGION_`_nn_ :
```ini
[coverage_intervals]
coverage=0
```

ShoRAH 1.99.0 has a bug when there are no reads in a BAM file.
It [will be fixed in ShoRAH 1.99.1](https://github.com/cbg-ethz/shorah/commit/b56771f2ce5bfb9d65f862fa9a6e45833585e0f0). 

(I know it's [the second time I am asking you to wait for that upgrade](https://github.com/cbg-ethz/shorah/issues/76) and I understand that I might be frustrating ;-) )

Possible work-around to flag the step as finished: 
```bash
touch samples/${negative}/${control}/variants/SNVs/snvs.{csv,vcf}
```
or just [ignore the error and keep going](https://snakemake.readthedocs.io/en/stable/executing/cli.html#EXECUTION):
```bash
./vpipe --jobs 8 --keep-going
```

Of course, this is assuming that an empty BAM file was expected (e.g.: negative control). If that's NOT the case, we need to investigate that closely together!
